package com.smy.fbsj.model;

import java.util.Date;

public class BaseUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_users.id
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_users.chan_add
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    private String chanAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_users.create_time
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_users.id_del
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    private Integer idDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_users.memo
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_users.id
     *
     * @return the value of base_users.id
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_users.id
     *
     * @param id the value for base_users.id
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_users.chan_add
     *
     * @return the value of base_users.chan_add
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public String getChanAdd() {
        return chanAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_users.chan_add
     *
     * @param chanAdd the value for base_users.chan_add
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public void setChanAdd(String chanAdd) {
        this.chanAdd = chanAdd == null ? null : chanAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_users.create_time
     *
     * @return the value of base_users.create_time
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_users.create_time
     *
     * @param createTime the value for base_users.create_time
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_users.id_del
     *
     * @return the value of base_users.id_del
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public Integer getIdDel() {
        return idDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_users.id_del
     *
     * @param idDel the value for base_users.id_del
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public void setIdDel(Integer idDel) {
        this.idDel = idDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_users.memo
     *
     * @return the value of base_users.memo
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_users.memo
     *
     * @param memo the value for base_users.memo
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}