package com.smy.fbsj.model;

import java.util.Date;

public class BaseUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_users.id
     *
     * @mbggenerated Mon Sep 10 17:45:45 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_users.chan_add
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private String chanAdd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_users.create_time
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_users.memo
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_users.id
     *
     * @return the value of base_users.id
     *
     * @mbggenerated Mon Sep 10 17:45:45 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_users.id
     *
     * @param id the value for base_users.id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_users.chan_add
     *
     * @return the value of base_users.chan_add
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public String getChanAdd() {
        return chanAdd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_users.chan_add
     *
     * @param chanAdd the value for base_users.chan_add
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setChanAdd(String chanAdd) {
        this.chanAdd = chanAdd == null ? null : chanAdd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_users.create_time
     *
     * @return the value of base_users.create_time
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_users.create_time
     *
     * @param createTime the value for base_users.create_time
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_users.memo
     *
     * @return the value of base_users.memo
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_users.memo
     *
     * @param memo the value for base_users.memo
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}