package com.smy.fbsj.model;

import java.util.Date;

public class SysSetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_setting.id
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_setting.user_url
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    private String userUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_setting.trade_url
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    private String tradeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_setting.life_url
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    private String lifeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_setting.create_time
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_setting.memo
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_setting.id
     *
     * @return the value of sys_setting.id
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_setting.id
     *
     * @param id the value for sys_setting.id
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_setting.user_url
     *
     * @return the value of sys_setting.user_url
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public String getUserUrl() {
        return userUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_setting.user_url
     *
     * @param userUrl the value for sys_setting.user_url
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public void setUserUrl(String userUrl) {
        this.userUrl = userUrl == null ? null : userUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_setting.trade_url
     *
     * @return the value of sys_setting.trade_url
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public String getTradeUrl() {
        return tradeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_setting.trade_url
     *
     * @param tradeUrl the value for sys_setting.trade_url
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public void setTradeUrl(String tradeUrl) {
        this.tradeUrl = tradeUrl == null ? null : tradeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_setting.life_url
     *
     * @return the value of sys_setting.life_url
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public String getLifeUrl() {
        return lifeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_setting.life_url
     *
     * @param lifeUrl the value for sys_setting.life_url
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public void setLifeUrl(String lifeUrl) {
        this.lifeUrl = lifeUrl == null ? null : lifeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_setting.create_time
     *
     * @return the value of sys_setting.create_time
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_setting.create_time
     *
     * @param createTime the value for sys_setting.create_time
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_setting.memo
     *
     * @return the value of sys_setting.memo
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_setting.memo
     *
     * @param memo the value for sys_setting.memo
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}