package com.smy.fbsj.model;

import java.util.Date;

public class SysSetting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_setting.id
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_setting.user_url
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    private String userUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_setting.trade_url
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    private String tradeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_setting.life_url
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    private String lifeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_setting.create_time
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_setting.host
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    private String host;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_setting.app_key
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_setting.app_secret
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    private String appSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_setting.memo
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_setting.id
     *
     * @return the value of sys_setting.id
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_setting.id
     *
     * @param id the value for sys_setting.id
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_setting.user_url
     *
     * @return the value of sys_setting.user_url
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public String getUserUrl() {
        return userUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_setting.user_url
     *
     * @param userUrl the value for sys_setting.user_url
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public void setUserUrl(String userUrl) {
        this.userUrl = userUrl == null ? null : userUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_setting.trade_url
     *
     * @return the value of sys_setting.trade_url
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public String getTradeUrl() {
        return tradeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_setting.trade_url
     *
     * @param tradeUrl the value for sys_setting.trade_url
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public void setTradeUrl(String tradeUrl) {
        this.tradeUrl = tradeUrl == null ? null : tradeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_setting.life_url
     *
     * @return the value of sys_setting.life_url
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public String getLifeUrl() {
        return lifeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_setting.life_url
     *
     * @param lifeUrl the value for sys_setting.life_url
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public void setLifeUrl(String lifeUrl) {
        this.lifeUrl = lifeUrl == null ? null : lifeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_setting.create_time
     *
     * @return the value of sys_setting.create_time
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_setting.create_time
     *
     * @param createTime the value for sys_setting.create_time
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_setting.host
     *
     * @return the value of sys_setting.host
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_setting.host
     *
     * @param host the value for sys_setting.host
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_setting.app_key
     *
     * @return the value of sys_setting.app_key
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_setting.app_key
     *
     * @param appKey the value for sys_setting.app_key
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_setting.app_secret
     *
     * @return the value of sys_setting.app_secret
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_setting.app_secret
     *
     * @param appSecret the value for sys_setting.app_secret
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret == null ? null : appSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_setting.memo
     *
     * @return the value of sys_setting.memo
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_setting.memo
     *
     * @param memo the value for sys_setting.memo
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}