package com.smy.fbsj.model;

import java.util.Date;

public class UserDyn_msg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dyn_msg.id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dyn_msg.user_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dyn_msg.rec_user
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Long recUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dyn_msg.content
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dyn_msg.img
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dyn_msg.type
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dyn_msg.create_time
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dyn_msg.good_num
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Integer goodNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dyn_msg.comm_num
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Integer commNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dyn_msg.forward_num
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Integer forwardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dyn_msg.memo
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dyn_msg.is_strange
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Integer isStrange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dyn_msg.is_forward
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Integer isForward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dyn_msg.forward_res
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private String forwardRes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_dyn_msg.msg_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Long msgId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dyn_msg.id
     *
     * @return the value of user_dyn_msg.id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dyn_msg.id
     *
     * @param id the value for user_dyn_msg.id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dyn_msg.user_id
     *
     * @return the value of user_dyn_msg.user_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dyn_msg.user_id
     *
     * @param userId the value for user_dyn_msg.user_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dyn_msg.rec_user
     *
     * @return the value of user_dyn_msg.rec_user
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Long getRecUser() {
        return recUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dyn_msg.rec_user
     *
     * @param recUser the value for user_dyn_msg.rec_user
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setRecUser(Long recUser) {
        this.recUser = recUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dyn_msg.content
     *
     * @return the value of user_dyn_msg.content
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dyn_msg.content
     *
     * @param content the value for user_dyn_msg.content
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dyn_msg.img
     *
     * @return the value of user_dyn_msg.img
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dyn_msg.img
     *
     * @param img the value for user_dyn_msg.img
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dyn_msg.type
     *
     * @return the value of user_dyn_msg.type
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dyn_msg.type
     *
     * @param type the value for user_dyn_msg.type
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dyn_msg.create_time
     *
     * @return the value of user_dyn_msg.create_time
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dyn_msg.create_time
     *
     * @param createTime the value for user_dyn_msg.create_time
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dyn_msg.good_num
     *
     * @return the value of user_dyn_msg.good_num
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Integer getGoodNum() {
        return goodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dyn_msg.good_num
     *
     * @param goodNum the value for user_dyn_msg.good_num
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setGoodNum(Integer goodNum) {
        this.goodNum = goodNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dyn_msg.comm_num
     *
     * @return the value of user_dyn_msg.comm_num
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Integer getCommNum() {
        return commNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dyn_msg.comm_num
     *
     * @param commNum the value for user_dyn_msg.comm_num
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setCommNum(Integer commNum) {
        this.commNum = commNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dyn_msg.forward_num
     *
     * @return the value of user_dyn_msg.forward_num
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Integer getForwardNum() {
        return forwardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dyn_msg.forward_num
     *
     * @param forwardNum the value for user_dyn_msg.forward_num
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setForwardNum(Integer forwardNum) {
        this.forwardNum = forwardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dyn_msg.memo
     *
     * @return the value of user_dyn_msg.memo
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dyn_msg.memo
     *
     * @param memo the value for user_dyn_msg.memo
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dyn_msg.is_strange
     *
     * @return the value of user_dyn_msg.is_strange
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Integer getIsStrange() {
        return isStrange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dyn_msg.is_strange
     *
     * @param isStrange the value for user_dyn_msg.is_strange
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setIsStrange(Integer isStrange) {
        this.isStrange = isStrange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dyn_msg.is_forward
     *
     * @return the value of user_dyn_msg.is_forward
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Integer getIsForward() {
        return isForward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dyn_msg.is_forward
     *
     * @param isForward the value for user_dyn_msg.is_forward
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setIsForward(Integer isForward) {
        this.isForward = isForward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dyn_msg.forward_res
     *
     * @return the value of user_dyn_msg.forward_res
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public String getForwardRes() {
        return forwardRes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dyn_msg.forward_res
     *
     * @param forwardRes the value for user_dyn_msg.forward_res
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setForwardRes(String forwardRes) {
        this.forwardRes = forwardRes == null ? null : forwardRes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_dyn_msg.msg_id
     *
     * @return the value of user_dyn_msg.msg_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Long getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_dyn_msg.msg_id
     *
     * @param msgId the value for user_dyn_msg.msg_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setMsgId(Long msgId) {
        this.msgId = msgId;
    }
}