package com.smy.fbsj.model;

import java.util.Date;

public class UserComments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comments.id
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comments.img
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    private Long img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comments.user_id
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comments.type
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comments.rec_user
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    private Long recUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comments.content
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comments.create_time
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comments.memo
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comments.id
     *
     * @return the value of user_comments.id
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comments.id
     *
     * @param id the value for user_comments.id
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comments.img
     *
     * @return the value of user_comments.img
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public Long getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comments.img
     *
     * @param img the value for user_comments.img
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public void setImg(Long img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comments.user_id
     *
     * @return the value of user_comments.user_id
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comments.user_id
     *
     * @param userId the value for user_comments.user_id
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comments.type
     *
     * @return the value of user_comments.type
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comments.type
     *
     * @param type the value for user_comments.type
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comments.rec_user
     *
     * @return the value of user_comments.rec_user
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public Long getRecUser() {
        return recUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comments.rec_user
     *
     * @param recUser the value for user_comments.rec_user
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public void setRecUser(Long recUser) {
        this.recUser = recUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comments.content
     *
     * @return the value of user_comments.content
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comments.content
     *
     * @param content the value for user_comments.content
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comments.create_time
     *
     * @return the value of user_comments.create_time
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comments.create_time
     *
     * @param createTime the value for user_comments.create_time
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comments.memo
     *
     * @return the value of user_comments.memo
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comments.memo
     *
     * @param memo the value for user_comments.memo
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}