package com.smy.fbsj.model;

import java.util.Date;

public class UserTimeStamp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_time_stamp.id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_time_stamp.user_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_time_stamp.udmsg_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Long udmsgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_time_stamp.is_mine
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Integer isMine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_time_stamp.create_time
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_time_stamp.id
     *
     * @return the value of user_time_stamp.id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_time_stamp.id
     *
     * @param id the value for user_time_stamp.id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_time_stamp.user_id
     *
     * @return the value of user_time_stamp.user_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_time_stamp.user_id
     *
     * @param userId the value for user_time_stamp.user_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_time_stamp.udmsg_id
     *
     * @return the value of user_time_stamp.udmsg_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Long getUdmsgId() {
        return udmsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_time_stamp.udmsg_id
     *
     * @param udmsgId the value for user_time_stamp.udmsg_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setUdmsgId(Long udmsgId) {
        this.udmsgId = udmsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_time_stamp.is_mine
     *
     * @return the value of user_time_stamp.is_mine
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Integer getIsMine() {
        return isMine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_time_stamp.is_mine
     *
     * @param isMine the value for user_time_stamp.is_mine
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setIsMine(Integer isMine) {
        this.isMine = isMine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_time_stamp.create_time
     *
     * @return the value of user_time_stamp.create_time
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_time_stamp.create_time
     *
     * @param createTime the value for user_time_stamp.create_time
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}