package com.smy.fbsj.model;

import java.util.Date;

public class UserAgree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_agree.id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_agree.user_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_agree.src_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Long srcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_agree.reason
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_agree.create_time
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_agree.friend_from
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private String friendFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_agree.type
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_agree.memo
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_agree.id
     *
     * @return the value of user_agree.id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_agree.id
     *
     * @param id the value for user_agree.id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_agree.user_id
     *
     * @return the value of user_agree.user_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_agree.user_id
     *
     * @param userId the value for user_agree.user_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_agree.src_id
     *
     * @return the value of user_agree.src_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Long getSrcId() {
        return srcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_agree.src_id
     *
     * @param srcId the value for user_agree.src_id
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setSrcId(Long srcId) {
        this.srcId = srcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_agree.reason
     *
     * @return the value of user_agree.reason
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_agree.reason
     *
     * @param reason the value for user_agree.reason
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_agree.create_time
     *
     * @return the value of user_agree.create_time
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_agree.create_time
     *
     * @param createTime the value for user_agree.create_time
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_agree.friend_from
     *
     * @return the value of user_agree.friend_from
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public String getFriendFrom() {
        return friendFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_agree.friend_from
     *
     * @param friendFrom the value for user_agree.friend_from
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setFriendFrom(String friendFrom) {
        this.friendFrom = friendFrom == null ? null : friendFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_agree.type
     *
     * @return the value of user_agree.type
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_agree.type
     *
     * @param type the value for user_agree.type
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_agree.memo
     *
     * @return the value of user_agree.memo
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_agree.memo
     *
     * @param memo the value for user_agree.memo
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}