package com.smy.fbsj.mapper;


import com.smy.fbsj.model.BaseUsers;

import java.util.List;
import java.util.Map;

public interface BaseUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_users
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_users
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int insert(BaseUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_users
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int insertSelective(BaseUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_users
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    BaseUsers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_users
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int updateByPrimaryKeySelective(BaseUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_users
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int updateByPrimaryKey(BaseUsers record);

    /**
      * @Description:  获取所有用户
      * @Pramers:      hp.id_del  int  可传参数
      * @return:       返回类型
     */
    List<BaseUsers> getAllUsers(Integer id_del);

    /**
      * @Description:  根据id或chan_add  获取用户
      * @Pramers:      可传参数  id_del
      * @return:       返回类型
     */
    BaseUsers getUserById(Map<Object,Object> hp);

}