package com.smy.fbsj.mapper;

import com.smy.fbsj.model.UserAgree;

import java.util.List;
import java.util.Map;

public interface UserAgreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_agree
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_agree
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int insert(UserAgree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_agree
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int insertSelective(UserAgree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_agree
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    UserAgree selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_agree
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int updateByPrimaryKeySelective(UserAgree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_agree
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int updateByPrimaryKey(UserAgree record);

    /**
      * @Description:  通过用户id  和关联用户  查询请求好友记录id
      * @Pramers:      传入参数
      * @return:       返回类型
     */
    Long selectByUserIdAndRecUser(long user_id, long rec_user);

    /**
      * @Description:  通过用户id 获取请求好友记录列表
      * @Pramers:      user_id
      * @Pramers:      id_del   非必填参数
      * @return:       返回类型
     */
    List<UserAgree> selectObjectListByUserId(Map<Object,Object> hp);

}