package com.smy.fbsj.mapper;

import com.smy.fbsj.model.UserFriends;

public interface UserFriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friends
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friends
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    int insert(UserFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friends
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    int insertSelective(UserFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friends
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    UserFriends selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friends
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    int updateByPrimaryKeySelective(UserFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friends
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    int updateByPrimaryKey(UserFriends record);
}