package com.smy.fbsj.mapper;

import com.smy.fbsj.model.UserTimeStamp;

import java.util.List;
import java.util.Map;

public interface UserTimeStampMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_time_stamp
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_time_stamp
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int insert(UserTimeStamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_time_stamp
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int insertSelective(UserTimeStamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_time_stamp
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    UserTimeStamp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_time_stamp
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int updateByPrimaryKeySelective(UserTimeStamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_time_stamp
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int updateByPrimaryKey(UserTimeStamp record);

    /**
      * @Description:  通过用户id 获取该用户的时间轴列表
      * @Pramers:      user_id
      * @Pramers:      id_del  非必填参数
      * @return:       返回类型
     */
    List<UserTimeStamp> selectByUserId(Map<Object,Object> par);

    /**
      * @Description:  通过消息id更新id_del
      * @Pramers:      传入参数
      * @return:       返回类型
     */
    int updateIdDelByMsgId(Map<Object,Object> par);


}