package com.smy.fbsj.mapper;

import com.smy.fbsj.model.UserTimeStamp;

public interface UserTimeStampMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_time_stamp
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_time_stamp
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int insert(UserTimeStamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_time_stamp
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int insertSelective(UserTimeStamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_time_stamp
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    UserTimeStamp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_time_stamp
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int updateByPrimaryKeySelective(UserTimeStamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_time_stamp
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int updateByPrimaryKey(UserTimeStamp record);
}