package com.smy.fbsj.mapper;

import com.smy.fbsj.model.UserComments;

public interface UserCommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comments
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comments
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    int insert(UserComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comments
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    int insertSelective(UserComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comments
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    UserComments selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comments
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    int updateByPrimaryKeySelective(UserComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comments
     *
     * @mbggenerated Mon Sep 10 17:45:46 CST 2018
     */
    int updateByPrimaryKey(UserComments record);
}