package com.smy.fbsj.mapper;

import com.smy.fbsj.model.UserDyn_msg;

import java.util.Map;

public interface UserDyn_msgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dyn_msg
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dyn_msg
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int insert(UserDyn_msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dyn_msg
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int insertSelective(UserDyn_msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dyn_msg
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    UserDyn_msg selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dyn_msg
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int updateByPrimaryKeySelective(UserDyn_msg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_dyn_msg
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int updateByPrimaryKey(UserDyn_msg record);

    /**
      * @Description:  根据传入column_value 更新
      * @Pramers:      column_value   实例：update user_dyn_msg set ? where id=?
      * @Pramers:      id   主键
      * @return:       返回类型
     */
    int updateBySetColunmValue(Map<Object,Object> par);

}