package com.smy.fbsj.mapper;

import com.smy.fbsj.model.UserFriends;

import java.util.List;
import java.util.Map;

public interface UserFriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friends
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friends
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int insert(UserFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friends
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int insertSelective(UserFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friends
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    UserFriends selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friends
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int updateByPrimaryKeySelective(UserFriends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friends
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int updateByPrimaryKey(UserFriends record);

    /**
      * @Description:  通过用户id 获取好友关系列表
      * @Pramers:      par {user_id=xxx,id_del=xxxx}
      * @return:       返回类型
     */
    List<UserFriends> getFriendListByuserId(Map<Object,Object> par);

}