package com.smy.fbsj.mapper;

import com.smy.fbsj.model.UserAgree;

public interface UserAgreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_agree
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_agree
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    int insert(UserAgree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_agree
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    int insertSelective(UserAgree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_agree
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    UserAgree selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_agree
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    int updateByPrimaryKeySelective(UserAgree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_agree
     *
     * @mbggenerated Thu Aug 30 17:05:47 CST 2018
     */
    int updateByPrimaryKey(UserAgree record);
}