package com.smy.fbsj.mapper;

import com.smy.fbsj.model.UserComments;

import java.util.Map;

public interface UserCommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comments
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comments
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int insert(UserComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comments
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int insertSelective(UserComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comments
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    UserComments selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comments
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int updateByPrimaryKeySelective(UserComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comments
     *
     * @mbggenerated Thu Sep 20 17:16:58 CST 2018
     */
    int updateByPrimaryKey(UserComments record);

    /**
      * @Description:  通过消息ID 修改记录id_del
      * @Pramers:      传入参数
      * @return:       返回类型
     */
    int updateByMsgIdSetIdDel(Map<Object,Object> par);

    /**
      * @Description:  通过and 组合条件查询对象
      * @Pramers:      msg_id   消息id
      * @Pramers:      user_id   用户id
      * @Pramers:      type   类型
      * @Pramers:      id_del   是否删除
      * @return:       UserComments
     */
    UserComments selectByWhereValue(Map<Object,Object> par);

}